# Generated by Django 4.2.2 on 2023-06-22 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='link',
        ),
    ]
